# Generated by Django 5.1.3 on 2024-11-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='content',
            new_name='comment',
        ),
    ]
