# Generated by Django 5.1.3 on 2024-11-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Broker', 'Broker'), ('Buyer', 'Buyer'), ('Investor', 'Investor'), ('Seller', 'Seller')], default='Buyer', max_length=30),
        ),
    ]
