# Generated by Django 5.1.3 on 2024-11-11 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[], max_length=100)),
                ('property_image', models.ImageField(upload_to='property_image/')),
                ('rooms', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('exposure', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0, message='Value must be greater than zero')])),
                ('address', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
