# Generated by Django 5.1.3 on 2024-11-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0005_remove_properties_address_remove_properties_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='postcode',
            field=models.CharField(default=1700, max_length=100),
            preserve_default=False,
        ),
    ]
