# Generated by Django 5.1.3 on 2024-11-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0007_alter_properties_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='type',
            field=models.CharField(choices=[('One-Bedroom Apartment', 'One-Bedroom Apartment'), ('Two-Bedroom', 'Two-Bedroom Apartment'), ('Three-Bedroom Apartment', 'Three-Bedroom Apartment'), ('Four-Bedroom Apartment', 'Four-Bedroom Apartment'), ('Maisonette', 'Maisonette'), ('Business Property', 'Business Property'), ('House', 'House'), ('Villa', 'Villa')], max_length=100),
        ),
    ]
