# Generated by Django 5.1.3 on 2024-11-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0011_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='parking',
            field=models.ManyToManyField(related_name='properties', to='real_estate.parking'),
        ),
    ]
