# Generated by Django 5.1.3 on 2024-11-25 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0012_properties_parking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='parking',
        ),
        migrations.AddField(
            model_name='properties',
            name='parking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='real_estate.parking'),
            preserve_default=False,
        ),
    ]
