# Generated by Django 5.1.3 on 2024-11-25 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0013_remove_properties_parking_properties_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='parking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='real_estate.parking'),
        ),
    ]
