# Generated by Django 5.1.3 on 2024-12-01 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0014_alter_properties_parking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='properties',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
